FROM python:3.8-slim as compiler
ENV PYTHONUNBUFFERED 1

WORKDIR /app/

RUN apt-get update &&  apt-get install -y libsndfile1
RUN python -m venv /opt/venv
# Enable venv
ENV PATH="/opt/venv/bin:$PATH"

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

FROM python:3.8-slim as runner
WORKDIR /app/
COPY --from=compiler /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"
COPY . /app/
CMD ["python", "main.py"]